### ISSUE TITLE
SciCookie Quality Checklist (based on pyopensci guideline)

### ISSUE THREAD

**Issue by EverVino** [osl-incubator/scicookie#230]
### Summary

Check list for scicookie as sci tool 
Reference [pyOpenSci](https://www.pyopensci.org/software-peer-review/how-to/editor-in-chief-guide.html#editor-checklist-template) 
- [x] **Installation** The package can be installed from a community repository such as PyPI (preferred), and/or a community channel on conda (e.g. conda-forge, bioconda).
- [ ] **Documentation** The package has sufficient online documentation to allow us to evaluate package function and scope *without installing the package*. This includes:
  - [ ] User-facing documentation that overviews how to install and start using the package.
  - [ ] Short tutorials that help a user understand how to use the package and what it can do for them. Additionally, how to create a profile file and push it.
  - [ ] ~API documentation (documentation for your code's functions, classes, methods and attributes): this includes clearly written docstrings with variables defined using a standard docstring format.~ (this is not a library, so maybe we don't need this right now).
- [x] Core GitHub repository Files
  - [x] **README** The package has a `README.md` file with clear explanation of what the package does, instructions on how to install it, and a link to development instructions.
  - [x] **Contributing File** The package has a `CONTRIBUTING.md` file that details how to install and contribute to the package.
  - [x] **Code of Conduct** The package has a `CODE_OF_CONDUCT.md` file.
  - [x] **License** The package has an [OSI approved license](https://opensource.org/licenses).
NOTE: We prefer that you have development instructions in your documentation too.
- [x] **Issue Submission Documentation** All of the information is filled out in the `YAML` header of the issue (located at the top of the issue template).
- [x] **Automated tests** Package has a testing suite and is tested via a Continuous Integration service.
- [x] **Repository** The repository link resolves correctly.

### Additional Information

```python (paste below)

```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by AayushSahani01** [comment]
can you assigned work me then I can contribute this repo project !
